# Generated by Django 3.1.1 on 2020-11-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='user_id',
        ),
    ]
