# Generated by Django 3.1.1 on 2020-11-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_package_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='package',
            name='pname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='ptype',
            field=models.TextField(max_length=20),
        ),
    ]
